-- 创建额外的数据库
CREATE DATABASE IF NOT EXISTS langsistance_db;

-- 创建知识表
USE langsistance_db;
CREATE TABLE  knowledge (
    id BIGINT UNSIGNED AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    question VARCHAR(100) NOT NULL,
	description VARCHAR(5000) NOT NULL Default '',
	answer VARCHAR(5000) NOT NULL,
	public BOOL NOT NULL,
    status BOOL NOT NULL,
	embedding_id BIGINT(64) UNSIGNED NOT NULL,
	model_name VARCHAR(200) NOT NULL Default '',
	tool_id BIGINT(64) UNSIGNED NOT NULL,
	params VARCHAR(5000) NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_user_id_status (user_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 创建工具表
CREATE TABLE  tools (
    id BIGINT UNSIGNED AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(100) NOT NULL,
	description VARCHAR(5000) NOT NULL,
	url VARCHAR(1000) NOT NULL,
	push TINYINT UNSIGNED NOT NULL,
	public BOOL NOT NULL,
    status BOOL NOT NULL,
	timeout SMALLINT UNSIGNED NOT NULL,
	params VARCHAR(5000) NOT NULL,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
    KEY idx_user_id_status (user_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 创建用户表
CREATE TABLE users (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT UNSIGNED UNIQUE NOT NULL,
    firebase_uid BIGINT UNSIGNED UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    hashed_password VARCHAR(255),
    oauth_provider VARCHAR(255),
    oauth_provider_id VARCHAR(255),
    is_active TINYINT UNSIGNED DEFAULT TRUE,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 创建知识授权表
CREATE TABLE knowledge_share (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    from_user_id BIGINT UNSIGNED NOT NULL,
    from_user_email VARCHAR(255) NOT NULL DEFAULT '',
    to_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    to_user_email VARCHAR(255) UNIQUE NOT NULL DEFAULT '',
    knowledge_id BIGINT UNSIGNED NOT NULL,
    status TINYINT UNSIGNED DEFAULT TRUE,
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;