-- 创建额外的数据库
CREATE DATABASE IF NOT EXISTS langsistance_db;

-- 创建知识表
USE langsistance_db;
CREATE TABLE  knowledge (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId VARCHAR(50) NOT NULL,
    question VARCHAR(100) NOT NULL,
	description VARCHAR(5000) NOT NULL,
	answer VARCHAR(5000) NOT NULL,
	public BOOL NOT NULL,
    status BOOL NOT NULL,
	embeddingId BIGINT(64) NOT NULL,
	model_name VARCHAR(200) NOT NULL,
	tool_id BIGINT(64) NOT NULL,
	params VARCHAR(5000) NOT NULL,
    creat_time DATATIME DEFAULT CURRENT_TIMESTAMP,
	update_time  DATATIME ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 创建工具表
CREATE TABLE  tools (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId VARCHAR(50) NOT NULL,
    title VARCHAR(100) NOT NULL,
	description VARCHAR(5000) NOT NULL,
	url VARCHAR(1000) NOT NULL,
	push TINYINT NOT NULL,
	public BOOL NOT NULL,
    status BOOL NOT NULL,
	timeout SMALLINT NOT NULL,
	params VARCHAR(5000) NOT NULL,
    creat_time DATATIME DEFAULT CURRENT_TIMESTAMP,
	update_time  DATATIME ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;